### ISSUE TITLE
Make mitosheet launchable on specific data frames from the command line

### ISSUE THREAD

**Issue by naterush** [mito-ds/mito#101]
**Is your feature request related to a problem? Please describe.**

I wanted to use Mito for a quick analysis - and doing so required getting data into Mito. I didn't have a mitosheet instance started up. 

I want to be able to really quickly launch mitosheet from the command line with some file paths as arguments, and get them in a mitosheet immediately.

**Describe the solution you'd like**

```
python -m mitosheet analyze path/to/file.csv
```

This should launch a JupyterLab instance with a notebook with this file in a cell, ready to be analyzed. I should just have to run it. This seems very doable!

**Describe alternatives you've considered**
We could do more complex things like adding icons, etc - but for my own usage of Mito (as a real, geniune user in this case), I think this solution would have been totally cool and really satisfactory. It's also pretty easy to do - we just need to reuse the infrastructure from the installer1

**Additional context**
No.

**Comment by aarondr77** [comment]
Other things along these lines, although more complex, would be to let the user download a Mito application, so that when they right click on a file, they can open with Mito. Which would have the same behavior that you just described. 

This would be great for the less technical Mito users.

**Comment by naterush** [comment]
I think that's a very cool feature! I also think it's a bit out of scope for this issue - it's a much bigger technical lift + needs much more thinking and specification.

Please open up another issue, if you want!
