### ISSUE TITLE
Global Dataframe State Bug in Dash

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1024]
Sorry I don't have time currently to create a minimal example. But see example here: https://drive.google.com/file/d/1xiJIKLmCTpeEhf_lt5fd-UmXuJViubzZ/view?usp=sharing

We should test if the same thing happens in Streamlit. 

In addition, you can see a temporary fix here: https://github.com/plotly/mito-dash-application/pull/2/commits/cdbdceeae5a93a6581cdc55fd360300305a9cd93

**Comment by naterush** [comment]
We just need to make a copy of the dataframes before passing them to the spreadsheet result. Nice catch here. I think df.copy() is a fine soulution for now.
