### ISSUE TITLE
CMD+A keyboard doesn't work in column header cell editor

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1095]
**Works in formulas**
1. Open a cell editor that has a formula in it
2. Press CMD + A to select the entire formula to edit. 
3. It works. Nice

**Does not work in column headers**
1. Open a column header 
2. Press CMD + A to select the entire column header to change
3. It closes the cell editor and selects the entire sheet.

https://github.com/mito-ds/mito/assets/18709905/6b76915a-e00b-4a3a-8adb-8b237954907e

**Comment by naterush** [comment]
This is an issue in the rename for dataframe headers as well. If you:
1. Open a dataframe header
2. Press Cmd + A to highlight it all

It highlights the sheet instead of the dataframe name.
