### ISSUE TITLE
Cannot open formula bar editor if floating cell editor is open

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1254]
1. Open the floating cell editor
2. Try to switch to the formula bar. Notice that you cannot open the formula bar unless you have first close the floating cell editor

Just like in Excel, users should be able to switch from the cell editor to the formula bar. This is important because users often switch when they are writing long formulas. We don't want users to have to close the cell editor, losing their formula, in the process.

**Comment by marthacryan** [comment]
Note here: this is only true if there is no value in the cell editor.
