### ISSUE TITLE
Not working with streamlit.file_uploader

### ISSUE THREAD

**Issue by DarkCTO** [mito-ds/mito#1292]
**Describe the bug**
If you run the code below, which creates /sessions if it doesn't exist, then upon uploading, the files are saved to the same session... However mitosheet seems to rerun everything when created making session id changed and all that.

**To Reproduce**
```
import streamlit as st
from mitosheet.streamlit.v1 import spreadsheet
import uuid

from pathlib import Path
Path("./sessions").mkdir(parents=True, exist_ok=True)

st.set_page_config(layout="wide")
st.title('Test')

session = uuid.uuid4().hex
st.write(f'Session: {session}')

uploaded_files = st.file_uploader(
    "Select File(s)", 
    accept_multiple_files=True,
    )
for uploaded_file in uploaded_files:
    Path(f"./sessions/{session}").mkdir(parents=True, exist_ok=True)
    bytes_data = uploaded_file.read()
    with open(f"{session}/{uploaded_file.name}", "wb") as binary_file:
        binary_file.write(bytes_data)

new_dfs, code = spreadsheet(None, import_folder=f'./sessions/')
st.write(new_dfs)
st.code(code)
```

Please include the relevant dataset if the bug you encountered is dataset specific. Make sure to anonymize the data properly.

**Expected behavior**
After files upload, I can find the files on mitosheet import

**Screenshots**

**Desktop (please complete the following information):**
```
                 `:osssssss+-              OS: EndeavourOS Linux x86_64 
               `:+sssssssssso/.            Host: 82K6 Legion 7 16ITHg6 
             `-/ossssssssssssso/.          Kernel: 6.8.1-arch1-1 
           `-/+sssssssssssssssso+:`        Uptime: 16 hours, 45 mins 
         `-:/+sssssssssssssssssso+/.       Packages: 1089 (pacman) 
       `.://osssssssssssssssssssso++-      Shell: bash 5.2.26 
      .://+ssssssssssssssssssssssso++:     Resolution: 2560x1080, 2560x1600 
    .:///ossssssssssssssssssssssssso++:    WM: i3 
  `:////ssssssssssssssssssssssssssso+++.   Theme: Adwaita [GTK2], Arc-Dark [GTK3] 
`-////+ssssssssssssssssssssssssssso++++-   Icons: Adwaita [GTK2], Qogir-dark [GTK3] 
 `..-+oosssssssssssssssssssssssso+++++/`   Terminal: xfce4-terminal 
   ./++++++++++++++++++++++++++++++/:.     Terminal Font: Source Code Pro 10 
  `:::::::::::::::::::::::::------``       CPU: 11th Gen Intel i9-11980HK (16) @ 4.900GHz 
                                           GPU: NVIDIA GeForce RTX 3080 Mobile / Max-Q 8GB/16GB 
                                           Memory: 6599MiB / 31949MiB 

```

`mitosheet==0.1.566`

**Additional context**
If I put the mkdir outside the uploaded_file event, it will just spawn multiple folders of different sessions.

**Comment by DarkCTO** [comment]
OK so this is streamlit behavior to re-run whenever users interact with it...

Temp fix:

```
if 'key' not in st.session_state:
    session = uuid.uuid4().hex
    st.session_state['key'] = session
else:
    session = st.session_state['key']
```

**Comment by naterush** [comment]
@DarkCTO glad you got it figured out. Mito caches the state of the spreadsheet based on the passed file paths - so you need to make sure these are static between runs. 

Your fix works around this by making sure the file path is the same in-between runs, and I think in practice is the correct long-term solution (it also stops you from needing to rewrite these files to a new folder every run.

**Comment by DarkCTO** [comment]
@naterush I would prefer to change the import folder to sessions, so that users don't have to navigate other sessions. But this works for now.

**Comment by DarkCTO** [comment]
My bad I'm really new to this streamlit thing, this will do:
`new_dfs, code = spreadsheet(None, import_folder=f'./sessions/{session}')`
