### ISSUE TITLE
Mito AI chat code diffs should revert to original state if not handled by user. 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1360]
Here is the issue: 
1. Generate code with AI 
2. Notice that the code is wrong, but don't Reject the AI code. Since you did not reject the AI code, the diffed code is still in the active cell
3. Send another message asking the AI to update the code. 
4. Now instead of seeing the diff between the original code and the AI generated code, you are seeing the diff between the diffed code from step 2 and the new AI generated code. That is completely not helpful. 

The solution for the user right now is for them to reject the code that they don't want after step 2, reverting the code cell back to the original state. But this is not a reasonable expectation and means our current solution is too fragile. Of course some users are going to skip the rejection step and just reprompt the AI. 

Here is one idea: If the user has not accepted or rejected the code the AI generated code, when the user either 1) starts typing in the input field or 2) the Ai taskpane loses focus (ie: the user is going to edit the notebook or something else) remove the code diff display and revert the code cell back to its original state.

**Comment by aarondr77** [comment]
This is pretty bad for users. If they don't accept or reject the code before creating a new message or clearing the chat, then the accept and reject buttons go away!

**Comment by ngafar** [comment]
We should definitely give this workflow some consideration. I'm partial to not showing the diff until the user asks for it. This way a user could prompt the AI, and get a suggestion. The suggestion would be shown in the sidebar, and from there the user would have the option to click an "Preview" button. Once the preview button has been clicked, we then show the diff, and prompt the user to accept/decline. 

We'd probably still need to test this, but I would assume the extra clicks would force uses to consider this as a workflow, i.e.: prompt -> preview -> accept/deny.
