### ISSUE TITLE
VariableManger returns an error when the objects are not serializable. 

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#1381]
When i call this function and the dataframe is: 

```
df = pd.DataFrame({'A': [pd.to_datetime('2020-01-01'), pd.to_datetime('2020-01-02'), pd.to_datetime('2020-01-03')]}, dtype=object)
```

I get this error: "Object of type Timestamp is not JSON serializable". This causes the variable manager to return an error and we don't update the variable manager at all. 

Currently, this means if a non-serializable dataframe is part of the global variables, we will never update the variable manager again. 

A simple fix is to put this in a try except block so we continue to update serializable objects even if we can't update the variable manager for every variable.

**Comment by aarondr77** [comment]
We have [a utility here](https://github.com/mito-ds/mito/blob/8ad504c4777e68a061ea07108a75bb0af999d647/mitosheet/mitosheet/utils.py#L503) that does what we want, so we just need to lift it out of the mitosheet package scope into a helper package

**Comment by ngafar** [comment]
Closing, see https://github.com/mito-ds/mito/pull/1392
