### ISSUE TITLE
[VariableManager] Variable Types Pushing Names Out of Alignment  

### ISSUE THREAD

**Issue by ngafar** [mito-ds/mito#1383]
See screenshot for examples of variable types that are problematic:

<img width="403" alt="Screenshot 2024-11-27 at 10 11 49 AM" src="https://github.com/user-attachments/assets/c5c0241c-aec2-4402-8ebd-3a15a5b3aad6">

Possible solution: set the variable type div to a fixed width.

**Comment by aarondr77** [comment]
Here's another example

<img width="349" alt="Screenshot 2024-11-27 at 11 45 55 AM" src="https://github.com/user-attachments/assets/7a39b9ce-e03d-4903-9567-4f03f85e33c6">

**Comment by ngafar** [comment]
Opened PR with fix: https://github.com/mito-ds/mito/pull/1405
