### ISSUE TITLE
CMD+Y to Preview Mito AI Code

### ISSUE THREAD

**Issue by ngafar** [mito-ds/mito#1423]
Add a shortcut to preview AI generated code. For simplicity it should be CMD+Y. This way users could use the same shortcut to preview and accept code changes.

**Comment by ngafar** [comment]
Additionally, be sure to add tests. It might make sense to add a separate spec file for testing shortcuts, just to keep things readable.

**Comment by aarondr77** [comment]
I think this is duplicate with https://github.com/mito-ds/mito/issues/1397

**Comment by ngafar** [comment]
So it is, and both have been completed as of https://github.com/mito-ds/mito/pull/1427
