### ISSUE TITLE
Tell the user what action is about to be undone/redone.

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#224]
Tell the user what action is about to be undone/redone. Maybe his could be in the tooltip or more explicit in the toolbar.

**Comment by naterush** [comment]
Can we break these out into two different issues? Also, adding waiting on mockups/specs for both of them - I think these require some thought...

**Comment by aarondr77** [comment]
Sure!

**Comment by aarondr77** [comment]
Implementation proposal:
1. For Undo, use the `stepSummaryList` that we already have in the state to determine the previous step that will be undone
2. For Redo, include the `undone_step_list_store` in the AnalysisData. It seems best to just use the backend's `undone_step_list_store` instead of trying to recreate it on the frontend so we don't have to redo logic.
