### ISSUE TITLE
Graph is incorrect size

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#235]
I've seen it a few times on user's computers that the graph generated is of an incorrect size. Mostly, I see this occur where the graph is smaller than the space it has, taking up only about 1/2 of the screen. However, I have also received word of the graph being too large such that the graph configuration taskpane gets cutoff. 

I haven't been able to reproduce this on my computer. So just opening this issue to start tracking.

**Comment by aarondr77** [comment]
One user has the graph so large that it cutoff the taskpane, and then the next day, when they continued graphing the graph was only 1/2 the screen. 

<img width="227" alt="Screen Shot 2022-04-15 at 9 13 48 AM" src="https://user-images.githubusercontent.com/18709905/163574915-388c8a67-3e87-4de2-a047-063b6463c46f.png">

**Comment by naterush** [comment]
@aarondr77 can you find out what browser this occurred on in the screen shot above? For this specific sort of bug, it makes investigations about 10x easier!

**Comment by aarondr77** [comment]
For sure. Just updated it
