### ISSUE TITLE
Escape should close the dataframe rename input

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#366]
Across the entire tool, using escape when an input it open should close the input without submitting the changes, reverting back to the previous state.

**Comment by naterush** [comment]
This is cool! I am thinking of a new component that:
1. Is an input.
2. Has props that allow it to watch for onEscape and onArrowPress

Then, we use this in the cell editor, in the renames, in the dropdown. Pretty much creating a component on top of a raw input that has a lot of the navigation functionality without needing to do a ton of explicit handling of the onKeyDown stuff...

Thoughts? What might this interface look like?

**Comment by naterush** [comment]
Fixed in https://github.com/mito-ds/monorepo/pull/401
