### ISSUE TITLE
Variable names for the code generated remains same for filter/sort operations 

### ISSUE THREAD

**Issue by sayantikabanik** [mito-ds/mito#464]
### Issue description 

After loading an existing CSV dataset using the mitosheet, I performed a few simple operations (sorting, filtering etc). The code generated for each operation appreares with same variable name. While the comments generated are accurate. Would be nice to have precise variable naming. 

### Version info (installed via `conda`)
```shell
mitoinstaller             0.0.180                  pypi_0    pypi
mitosheet                 0.1.446                  pypi_0    pypi
```

### Screenshot for reference 
<img width="981" alt="Screenshot 2022-09-08 at 2 11 56 PM" src="https://user-images.githubusercontent.com/17350312/189080268-2281ffbb-3e4e-4ba7-94e9-761f4115b96c.png">

**Comment by aarondr77** [comment]
Hey @sayantikabanik thanks for posting. I'm not sure I understand what the expected outcome is. Do you mind sharing a version of the code above that has the variable names how you expect them?

**Comment by sayantikabanik** [comment]
I expected the below outcome wrt to variable naming (something similar/close) -
```python
TWLO_stock_ordered_asc = ...
TWLO_stock_filtered = ...
```
Helps me to clearly distinguish the operation performed :)

**Comment by immanonner** [comment]
Are the 'cliff notes' in the direct line above the operation not cutting it?

**Comment by naterush** [comment]
Hey @sayantikabanik, we added features that let you rename a dataframe, and it will get included in the filter line above. This code optimization I think makes the above possible! So simply:
1. Filter a dataframe
2. Rename it
3. You'll see the generated code will optimize to do this one one line.
