### ISSUE TITLE
Filtering on datetime column gives temporary error when not typing quickly enough

### ISSUE THREAD

**Issue by plasmonresonator** [mito-ds/mito#581]
When a user tries to filter a date column and types the date in manually and not quickly enough, an execution error screen pops up even  though the filter is applied properly when the users completes typing in the date correctly.

**Steps to reproduce:**

- Open any dataframe in mito that has a datetime column.
- Add a filter to that datetime column and select >= from the dropdown menu.
- Begin typing in a date starting with month and day (e.g., 10, 30)
- When you get to the year, type 20, then pause for a moment and an error will appear.
- Continue typing the year 2022 and see that the filter is applied to the column correctly.

**Expected behavior:**
- Either the error should not appear at all provided a valid year is entered within a reasonable amount of time, or the error window should disappear when the user enters a valid date so they don't have to close the error screen and/or wonder if the filter was properly applied.

**Actual behavior:**
- Execution error window appears and has to be manually closed.
- Error message below

![image](https://user-images.githubusercontent.com/36050529/208920435-718d5f53-bd4c-43e1-9578-cc02634cc9de.png)

### **Bonus bug within a bug :-) **
Unable to copy the text from the full traceback (hence the screenshot of the partial message).  When highlighting the text of the traceback, it appears to actually be copying some of the text in the column it was filtering on.

**Comment by naterush** [comment]
Good bug report. @aarondr77 thoughts on making filter errors in-place? I think this would pretty much resolve this issue (something minor would come up while typing but would then disappear). 

We might have to do what we do with conditional formats, in so far as we give them IDs so we can easily match which is failing. Alternatively we could just use the filter or group index, and that would probably be fine (and not require a step upgrade)
