### ISSUE TITLE
Support more date formats

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#60]
**Describe the bug**
Mito should detect the date format, 17.14.11 (YY.DD.MM) and successfully convert it to a pandas datetime. 

We should figure out all of the most popular date formats and make sure Mito supports all of them.

**Comment by twelsh37** [comment]
You should definitely consider non-American date formats. 
From [w3School](https://www.w3.org/International/questions/qa-date-format#:~:text=The%20format%20MM%2FDD%2FYY,be%20slashes%2C%20dashes%20or%20periods.)

"The format MM/DD/YY is unique to the United States (but sometimes used in Canada, too, which can obviously create some confusion there). Most of Europe uses DD/MM/YY. Japan uses YY/MM/DD. The separators may be slashes, dashes or periods."

Like the UK. Standard Date format?
DD.MM.YYYY 
DD/MM/YYYY
DD-MM-YYYY
and then the same as above but with only a 2 digit YY but that's just heading to a Y3K bug
