### ISSUE TITLE
Bug with error traceback 

### ISSUE THREAD

**Issue by naterush** [mito-ds/mito#66]
The traceback for the column dependent error is not working. 

### To reproduce:
1. Import data
2. Add a new column and set its formula equal to another column, ex: `=A`
3. Delete column A
4. Click to display the error traceback and notice that it doesn't provide any information

<img width="1249" alt="Screen Shot 2022-02-13 at 2 38 51 PM" src="https://user-images.githubusercontent.com/18709905/153771737-0d075ee0-48e3-4fe3-97ab-5cf860793691.png">

**Comment by joshuahamlet** [comment]
I was checking this out but I couldn't reproduce. It looks like it allows me to delete without the error. 

![issue66](https://user-images.githubusercontent.com/19663396/234995329-c80543f8-434a-459c-8b0f-71f21013f36d.png)

Maybe there's some detail I'm missing.
