### ISSUE TITLE
pip build fail FileNotFoundError: [Errno 2] No such file or directory: 'mitosheet'  

### ISSUE THREAD

**Issue by cardifquang** [mito-ds/mito#673]
I tried to install mito in a Docker Image using:

```
RUN pip install --no-cache-dir mitosheet
RUN jupyter nbextension install mitosheet
RUN jupyter nbextension enable mitosheet
```

then using:

```
RUN pip install --no-cache-dir mitosheet
RUN jupyter nbextension install --user mitosheet
RUN jupyter nbextension enable mitosheet
```

The first step `RUN pip install --no-cache-dir mitosheet` ran succesfully.
But the installation failed at the second step. Here are the full traceback:

<html>
<body>

Mar 27 2023 17:28:24 +0200 | #11 [ 7/10] RUN jupyter nbextension install --user mitosheet |   |   |  
-- | -- | -- | -- | --
Mar 27 2023 17:28:24 +0200 | #11 0.745 Copying: mitosheet -> /home/ubuntu/.local/share/jupyter/nbextensions/mitosheet |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.745 Traceback (most recent call last): |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.745   File "/opt/conda/bin/jupyter-nbextension", line 8, in <module> |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.745     sys.exit(main()) |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.745   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.745     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs) |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.745   File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 846, in launch_instance |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.746     app.start() |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.746   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 972, in start |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747     super().start() |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 253, in start |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747     self.subapp.start() |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 702, in start |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747     self.install_extensions() |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 675, in install_extensions |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747     full_dests = install(self.extra_args[0], |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 191, in install_nbextension |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747     _maybe_copy(src, full_dest, logger=logger) |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 1030, in _maybe_copy |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747     shutil.copy2(src, dest) |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/shutil.py", line 444, in copy2 |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.748     copyfile(src, dst, follow_symlinks=follow_symlinks) |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.748   File "/opt/conda/lib/python3.9/shutil.py", line 264, in copyfile |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.748     with open(src, 'rb') as fsrc: |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:24 +0200 | #11 0.748 FileNotFoundError: [Errno 2] No such file or directory: 'mitosheet' |   |   |  
Mar 27 2023 17:28:24 +0200 |   |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 ERROR: process "/bin/sh -c jupyter nbextension install --user mitosheet" did not complete successfully: exit code: 1 |   |   |  
Mar 27 2023 17:28:25 +0200 | ------ |   |   |  
Mar 27 2023 17:28:25 +0200 | > [ 7/10] RUN jupyter nbextension install --user mitosheet: |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.747     full_dests = install(self.extra_args[0], |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 191, in install_nbextension |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.747     _maybe_copy(src, full_dest, logger=logger) |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 1030, in _maybe_copy |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.747     shutil.copy2(src, dest) |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.747   File "/opt/conda/lib/python3.9/shutil.py", line 444, in copy2 |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.748     copyfile(src, dst, follow_symlinks=follow_symlinks) |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.748   File "/opt/conda/lib/python3.9/shutil.py", line 264, in copyfile |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.748     with open(src, 'rb') as fsrc: |   |   |  
Mar 27 2023 17:28:25 +0200 | #11 0.748 FileNotFoundError: [Errno 2] No such file or directory: 'mitosheet' |   |   |  
Mar 27 2023 17:28:25 +0200 | ------ |   |   |  
Mar 27 2023 17:28:25 +0200 | Build failed: failed to solve: process "/bin/sh -c jupyter nbextension install --user mitosheet" did not complete successfully: exit code: 1

</body>
</html>

**Comment by naterush** [comment]
@cardifquang sorry for the issue here! Not sure exactly what the problem is from the logs, but it looks like there's some issue with Jupyter specifically. 

Do you need classic Jupyter Notebook support? If not, you can leave out the final two commands entirely. Mito just works with a `pip install` command in JupyterLab 3.0 and greater. 

Thanks for the issue!
