### ISSUE TITLE
Copy and Paste Out of Mito

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#71]
**Is your feature request related to a problem? Please describe.**
One of the primary ways that users get data into and out of other spreadsheet tools is by copying / pasting the data. The process of getting data into Mito is more formal. Its a several step process, and becomes even more burdensome if the file is not in the same directory that you have launched Jupyter from. 

**Describe the solution you'd like**
Users should be able to copy data from an Excel or CSV file into Mito, and they should be able to copy data from Mito into an Excel or CSV file. 

**Describe alternatives you've considered**
The alternatives are using Mito's import and export features, which work, but take more steps + time.

**Comment by naterush** [comment]
Some thoughts:
1. Copying out seems like the really high-value thing here. We don't really observe users doing single cell edits often, and I've never seen users chaining whole columns, etc.  Implementation should def start here.
2. Copying in is kinda an ill-defined operation... what does this really mean? Does it overwrite a block of the data frame? What are the limitations? 

For these reasons, I'm gonna ask that we a) turn this into into "copy and paste out of a mitosheet", and b) we open a new issue for copy and paste into a mitosheet, if we want to. I think the copy and paste in is a much lower priority / very different thing!

**Comment by naterush** [comment]
# Implementation Details

## Google Sheets Behavior

If you open Finder > Edit > Show Clipboard, you can see what's on your clipboard. I used this to figure out the contents of the clipboard after a copy in a few cases.

<img width="359" alt="Screen Shot 2022-03-02 at 11 22 00 AM" src="https://user-images.githubusercontent.com/21002431/156433590-4d024f0c-c9be-4fec-97bf-8d8ee9ced331.png">

### Copying a single cell

```
1
```


### Copying a single column

```
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

1
--
2
3
4

</google-sheets-html-origin>
```

### Copying a rectangular range including the first row

```
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

1 | 5
-- | --
2 | 6
3 | 7
4 | 8

</google-sheets-html-origin>
```

### Rectangular range, not including first row

```
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

2 | 6
-- | --
3 | 7
4 | 8

</google-sheets-html-origin>
```

### Rectangular range including an empty cell

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

1 | 5
-- | --
2 | 6
3 | 7
4 | 8
  | 9

</google-sheets-html-origin>

### Two different selections, same length, next to each other

```
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

1 | 5
-- | --
2 | 6
3 | 7
4 | 8

</google-sheets-html-origin>
```

### Two different sections, same length, not next to eachother

```
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

2 | 11
-- | --
3 | 12
4 | 13

</google-sheets-html-origin>
```


### Two different sections, different length, not next to eachother

```
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

12
--
13

</google-sheets-html-origin>
```


NOTE: it just took the second one in this case

**Comment by naterush** [comment]
# Thoughts on our implementation

## What to copy to the clipboard

If there is a single cell highlighted: we just copy the contents of that cell. 
If there is a single selection highlighted: we copy the full selection. 
If there are multiple selections, and they are selecting the same rows: we "append them" horizontally, and copy all of them.
If there are multiple selections, and they are selecting different rows: we take the selection that has the lowest row.

We treat column headers as a normal header in above. If there is ever more than one row that we are copying, we set apart the first row that is copied by a bar, so that it becomes a header (per Google Sheets, this is true even if they do not include the header).

The data we copy to the clipboard is 



## On targets for evaluation

I want to be able to effectively copy to the following applications with no issues:
1. Excel
2. Google Sheets
3. Notion
4. Powerpoint

These 4 applications working are what we're targeting for acceptance criteria. What 

TODO: figure out what 

## On strange data in what we're copying

## ON HTML tags


I do not think we need to start with HTML tags; I believe that copying with just the side by side bar structure is enough that we will be able to copy and paste into many different apps. 

## Detecting `command + c` or `control + c`
