### ISSUE TITLE
"try Mito" on homepage with Mitolight causes error

### ISSUE THREAD

**Issue by rs38** [mito-ds/mito#843]
https://mito-ds.github.io/mitolite/lab/
`Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.segment.io/v1/batch'.`

Press Shift + Enter 2 times to run all cells in this notebook for causing the error

 - Windows 11, Edge

**Comment by naterush** [comment]
@rs38 thanks for the bug report. We moved from JupyterLite to Streamlit for this reason -- let me know if it works for you now!

**Comment by rs38** [comment]
@naterush strange, I do not find a link or jump page or mentioning of the new "try online" with Streamlit?!
