### ISSUE TITLE
Mito AI Recon is Broken

### ISSUE THREAD

**Issue by aarondr77** [mito-ds/mito#997]
The Mito AI recon in mitosheet version 0.1.522 always returns `No changes`. 

<img width="1444" alt="Screenshot 2023-10-30 at 9 55 55 AM" src="https://github.com/mito-ds/mito/assets/18709905/b0148b37-3229-4ecc-89d1-145e05b2049a">

Hopefully this is fixed by https://github.com/mito-ds/mito/pull/941

**Comment by naterush** [comment]
@aarondr77 wacky. Did you do any investigation? How is this broken but our tests pass...

**Comment by aarondr77** [comment]
I did not. Just noticed it while trying to prep for a demo of the AI features
